name: escuela_virtual_modelaje
description: Frontend Flutter (Web + Android/iOS) para Escuela Virtual de Modelaje
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.5.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  url_launcher: ^6.3.2
  chewie: ^1.12.1
  video_player: ^2.10.0
  responsive_framework: ^1.5.1
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lock.svg
    - assets/logo.svg
