name: pagina_web
description: Proyecto Flutter con backend
publish_to: 'none' # evita publicar accidentalmente
version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
