name: elevare_full
description: Escuela Virtual de Modelaje - Frontend Flutter (Web + App)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.2.2
  shared_preferences: ^2.2.3
  go_router: ^14.8.1
  chewie: ^1.7.5
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
